import Login from "./Login";
import About from "./About";
import Home from "./Home";
import ADStudio from "./ADStudio";
import ADTrainer from "./ADTrainer";
import MyProfile from "./MyProfile";
import TeacherLanding from "./TeacherLanding";
import MyCourse from "./MyCourse";
import CourseList from "./CourseList";
import CourseDetails from "./CourseDetails";
import SearchResult from "./SearchResult";
import ADStudent from "./ADStudent";
import ContactUs from "./ContactUs";
import StudentProfile from "./StudentProfile";
import MyCart from "./MyCart";
import StudentProfileView from "./StudentProfileView";
import MyBlog from "./MyBlog";
import BlogList from './BlogList';
import PaymentSuccess from "./PaymentSuccess";
import CookiePolicy from "./CookiePolicy";
import PrivacyPolicy from "./PrivacyPolicy";
import TermConditions from "./TermConditions";
import MyOrder from "./MyOrder";
import MySales from "./MySales";

export {Login, About, Home, ADStudio, ADTrainer, MyProfile, MyCourse, CourseDetails, SearchResult, TeacherLanding, CourseList, ContactUs, ADStudent,StudentProfile,MyCart,StudentProfileView, MyBlog, BlogList, PaymentSuccess, CookiePolicy, PrivacyPolicy,TermConditions, MyOrder, MySales};
