import Header from './Header';
import Footer from './Footer';
import NotFound from './NotFound';
import LoginModal from './LoginModal';
import JoinAsStudent from './JoinAsStudent';
import JoinAsTrainer from './JoinAsTrainer';
import HeaderTrainer from './HeaderTrainer';
import HeaderStudent from './student/HeaderStudent';
import Login from './Login';
export {Header, Footer, LoginModal, JoinAsStudent, JoinAsTrainer, HeaderTrainer, NotFound, HeaderStudent,Login};